### PR TITLE
Update implementations.md

### PR DESCRIPTION
**Pull request by niko-ng**

### CODE REVIEW

**Comment by ept** [comment]
Thanks!

**Comment by niko-ng** [comment]
Thanks to you! for the inclusion in crdt.tech, and for your many contributions to CRDTs!
NextGraph is based on your BEC paper and integrates automerge library.
Looking forward meeting you one day ;)

**Comment by ept** [comment]
Glad to hear it! Would be nice to meet, maybe at the next local-first conference?

**Comment by niko-ng** [comment]
That would be great indeed :) Do you know more or less when we can expect the next conference?
Looking forward!

**Comment by ept** [comment]
No idea, sorry. But the last one went so well that it seems very likely to be continued.

**Pull request merged**
