### PR TITLE
papers.bib: add my Bachelor's Thesis

### PR DESCRIPTION
**Pull request by ttaylorr**
This pull request adds my Bachelor's thesis on verifying SEC in delta-state CRDTs to the list of papers. Please double check my formatting, since I think this is the first BS thesis in the collection.

Thanks! 😄 

##

### CODE REVIEW

**Comment by bieniusa** [comment]
Thank you for the entry!
I am not sure whether @techreport is the best choice here - they have a very special meaning, since universities are required to maintain their access and involve some numbering etc.
Unfortunately, bibtex offers only master thesis and phd thesis entry types. 

Did you try publishing your thesis as a technical report at your university?

**Comment by marc-shapiro** [comment]
bibtex also supports bachelor theses:

@MastersThesis{x,
  ...
  type = 	 {Bachelors' Thesis},
  ...
}

						Marc

**Comment by ept** [comment]
I tweaked the BibTeX entry and merged it. Thank you @ttaylorr, and congratulations on your thesis, it looks interesting! Great to see more people using Isabelle 😎

**Comment by ttaylorr** [comment]
Thanks, everybody! I'm sorry for not making these changes myself, I've been moving and haven't had much of a chance to open my laptop. It's great to see so many familiar names in this thread :).

**Pull request merged**
