### PR TITLE
Add Microsoft's recently open sourced Fluid Framework

### PR DESCRIPTION
**Pull request by mattheworiordan**
https://www.infoq.com/news/2020/12/fluid-framework-open-source-msft/

### CODE REVIEW

**Comment by dmonad** [comment]
Fluid doesn't implement a CRDT. It depends on a central authority to achieve a unique order of messages.

**Comment by marc-shapiro** [comment]
Just depending on a central authority does not exclude being a CRDT.  The CRDT question is:  Does Fluid support concurrent updates, and if so, does it merge them by leveraging commutativity?

                                Marc

**Comment by dmonad** [comment]
They clarify it now on their website:

> Does Fluid use CRDT?
> Fluid does not use Conflict-Free Replicated Data Types (CRDTs), but our model is more similar to CRDT than OT. The Fluid Framework relies on update-based operations that are ordered using our Total Order Broadcast to prevent conflicts. This allows us to have non-commutative operations because there is an explicit ordering

https://fluidframework.com/docs/faq/#does-fluid-use-crdt

**Comment by mattheworiordan** [comment]
If you only allow strict CRDT implementations, then I am happy to close this PR.  

I understood, perhaps incorrectly, that some of the implementations were not strictly all CRDT, but sometimes inspired by CRDT concepts.  I thought Logux fell into this camp, but I could be mistaken.

I don't feel strongly either way, I thought it was a useful addition as I recently came across it.

**Comment by ept** [comment]
One solution would be to have a "CRDT-related" section for things that are not strictly CRDTs, but which might be of interest to people exploring this space. In the papers list we already have some entries tagged with the "crdt-related" keyword if they are not strictly about CRDTs, but still relevant. What do you think?

**Comment by dmonad** [comment]
I wonder what makes Fluid similar to a CRDT. 

@ept I agree with you that Fluid is relevant to people exploring the space of automatic conflict resolution. But so are OT, diff-match-patch, ProseMirror's reconciliation approach, and many others.

**Comment by bieniusa** [comment]
I was thinking along the lines of @ept - why not make it a separate section / tag for related ideas? This allows people to sort and search quickly. We can add topics that @dmonad named over time.

It would be even more valuable to differentiate further by naming aspects like "relies on total order obtained by server" or "does not support offline" or "is not intention-preserving", but this might induce some work.

**Comment by marc-shapiro** [comment]
Good approach

		Marc

**Comment by mattheworiordan** [comment]
I can modify this PR and propose a new section, however it's probably easier to get some consensus here.

I propose adding a new section, at the bottom of the "Implementations" page, titled "Related projects" with the subtext "Libraries and applications that are inspired by, but do not formally implement CRDTs"

WDYT?

**Comment by dmonad** [comment]
> Libraries and applications that are inspired by, but do not formally implement CRDTs

There are no indications that Fluid uses any CRDT concepts. I'm concerned that adding Fluid to this website will fuel the notion that Fluid is "similar to a CRDT". What qualifies for being "similar to a CRDT"? It is not helpful to the reader to fuel this misconception.

I'm not against adding Fluid. I just hope that the approaches are clearly separated. I recommend to open a new section "Other approaches for automatic conflict resolution".
-------- Original Message --------

**Comment by dmonad** [comment]
I also like the tagging approach from @bieniusa 👍

**Comment by mattheworiordan** [comment]
Does 002d743 work?

**Comment by dmonad** [comment]
Thanks, it does for me. Although I'm just a contributor here.

**Comment by ept** [comment]
I like this. Thank you @mattheworiordan!

**Pull request merged**
